pipeline {
  agent any

  tools {
    nodejs 'Node 24'
  }

  stages {
    stage('Install dependencies') {
      steps {
        dir('frontend') {
          sh 'npm ci'
        }
      }
    }

    stage('Run tests') {
      steps {
        dir('frontend') {
          sh 'npm test'
        }
      }
    }

    stage('Build app') {
      steps {
        dir('frontend') {
          sh 'npm run build'
        }
      }
    }
  }
}