pipeline {
  agent any

  tools {
    nodejs 'Node 24'
  }

  environment {
    USERNAME = credentials('username')
    HOST = credentials('host')
  }

  stages {
    stage('Install dependencies') {
      steps {
        dir('frontend') {
          sh 'npm ci'
        }
      }
    }

    stage('Run tests') {
      steps {
        dir('frontend') {
          sh 'npm test'
        }
      }
    }

    stage('Build app') {
      steps {
        dir('frontend') {
          sh 'npm run build'
        }
      }
    }

    stage('Deploy') {
      steps {
        sshagent(['key']) {
          dir('frontend') {
            sh '''
              echo "Deploying to server..."
              scp -r build/* ${USERNAME}@${HOST}:/var/www/frontend/
              echo "Deployment done."
            '''
          }
        }
      }
    }
  }
}