pipeline {
  agent any

  environment {
    DOTNET_CLI_TELEMETRY_OPTOUT = "1"
    USERNAME = credentials('username')
    HOST = credentials('host')
  }

  stages {
    stage('Restore') {
      steps {
        dir('backend') {
          sh 'dotnet restore'
        }
      }
    }

    stage('Build') {
      steps {
        dir('backend') {
          sh 'dotnet build --no-restore --configuration Release'
        }
      }
    }

    stage('Test') {
      steps {
        dir('backend') {
          sh 'dotnet test --no-build --configuration Release'
        }
      }
    }

    stage('Publish') {
      steps {
        dir('backend') {
          sh 'dotnet publish -c Release -o publish'
        }
      }
    }

    stage('Deploy') {
      steps {
        sshagent(['key']) {
          dir('backend') {
            sh '''
              echo "Deploying backend to server..."
              scp -r publish/* ${USERNAME}@${HOST}:/var/www/backend/
              ssh ${USERNAME}@${HOST} "sudo systemctl restart backend.service"
              echo "Deployment complete and service restarted."
            '''
          }
        }
      }
    }
  }
}
